apiforllmdjango/urls.py
from django.contrib import admin
from django.urls import path, include
from base.forms import AuthAdminForm
from django.conf.urls import handler400, handler403, handler404, handler500
from base import views as base_views

admin.site.login_form = AuthAdminForm
admin.site.login_template = 'registration/login.html'

urlpatterns = [
    path("obscure/", admin.site.urls),
    path("", include("base.urls")),
    path("", include("main.urls")),
]

handler400 = base_views.handler400
handler403 = base_views.handler403
handler404 = base_views.handler404
handler500 = base_views.handler500

base/urls.py
from django.urls import path
from .views import AboutPage, SignupView, ProfileView, CustomPasswordResetView, CustomLoginView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("about/", AboutPage.as_view(), name="aboutpage"),
    path("login/", CustomLoginView.as_view(redirect_authenticated_user=True), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("password_reset/", CustomPasswordResetView.as_view(), name="password_reset"),
    path("password_reset_done/", auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("password_reset_confirm/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("password_reset_complete/", auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('signup/', SignupView.as_view(), name='signup'),
    path("password_change/", auth_views.PasswordChangeView.as_view(), name="password_change"),
    path("password_change_done/", auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),
    path('profile/', ProfileView.as_view(), name='profile'),
]

main/urls.py
from django.urls import path
from .views import HomePage, Chats, ChatMessageList, FunctionsView, TemplatesView, CreateChatView

urlpatterns = [
    path("", HomePage.as_view(), name="homepage"),
    path("chats/", Chats.as_view(), name="chats"),
    path('api/chats/<int:session_id>/', ChatMessageList.as_view(), name='chat_messages'),
    path("functions/", FunctionsView.as_view(), name="functions"),
    path("templates/", TemplatesView.as_view(), name="templates"),
    path("create-chat/", CreateChatView.as_view(), name="create_chat"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from decimal import Decimal
from django.utils import timezone
from cryptography.fernet import Fernet
import base64
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver

class SecretKey(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200)
    key = models.TextField(db_column='key')
    is_public = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def decrypt_key(self):
        f = Fernet(base64.urlsafe_b64encode(settings.SECRET_KEY.encode()[:32]))
        return f.decrypt(self.key.encode()).decode()

    def encrypt_key(self, new_key):
        f = Fernet(base64.urlsafe_b64encode(settings.SECRET_KEY.encode()[:32]))
        self.key = f.encrypt(new_key.encode()).decode()

    def __str__(self):
        return f'API Key {self.name} of {self.user}' if self.user else f'Public API Key {self.name}'

class FunctionSchema(models.Model):
    name = models.CharField(max_length=64)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    schema = models.JSONField()
    is_public = models.BooleanField(default=False)
    network_access = models.BooleanField(default=False)
    secrets = models.ManyToManyField(SecretKey, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class ChatTemplate(models.Model):
    name = models.CharField(max_length=64)
    model = models.CharField(max_length=64)
    temperature = models.FloatField()
    functions = models.ManyToManyField(FunctionSchema, blank=True)
    system_prompt = models.CharField(max_length=10000)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_public = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class FunctionServer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200)
    ip_address = models.GenericIPAddressField(protocol='both', unpack_ipv4=True, null=True, blank=True)
    hostname = models.CharField(max_length=200, null=True, blank=True)
    is_public = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class ChatSession(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    template = models.ForeignKey(ChatTemplate, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    flagged = models.BooleanField(default=False)
    function_approval_required = models.BooleanField(default=True)
    function_server = models.ForeignKey(FunctionServer, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class RoleChoices(models.TextChoices):
    SYSTEM = 'system',
    USER = 'user',
    ASSISTANT = 'assistant',
    FUNCTION = 'function',

class ChatMessage(models.Model):
    session = models.ForeignKey(ChatSession, on_delete=models.CASCADE, related_name='messages')
    role = models.CharField(max_length=10, choices=RoleChoices.choices)
    content = models.CharField(max_length=40000)
    input_cost = models.DecimalField(max_digits=10, decimal_places=9, default=Decimal('0.0'))
    output_cost = models.DecimalField(max_digits=10, decimal_places=9, default=Decimal('0.0'))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

    @receiver(post_save, sender=ChatSession)
    def create_initial_message(sender, instance, created, **kwargs):
        if created:  # if a new instance of ChatSession is created
            ChatMessage.objects.create(
                session=instance,
                role=RoleChoices.SYSTEM,
                content=instance.template.system_prompt,
                input_cost=Decimal('0.0'),
                output_cost=Decimal('0.0'),
            )

class UserBalance(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    balance = models.DecimalField(max_digits=16, decimal_places=9, default=Decimal('0.0')) 
    last_credit = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def debit(self, amount):
        if self.balance > 0 and self.balance - amount >= Decimal('0.0'):
            self.balance -= amount
            self.save()
        else:
            raise ValueError("Insufficient balance")

    def credit(self, amount):
        self.balance += amount
        self.last_credit = timezone.now()
        self.save()

    def reset_balance(self, amount=Decimal('0.0')):
        self.balance = amount
        self.last_credit = timezone.now()
        self.save()

main/forms.py
from django import forms
from .models import ChatMessage, SecretKey, ChatTemplate, ChatSession
from django.core.exceptions import ValidationError
from django.db.models import Q

class ChatTemplateAdminForm(forms.ModelForm):
    system_prompt = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = ChatTemplate
        fields = '__all__'

class ChatMessageAdminForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = ChatMessage
        fields = '__all__'
    
class SecretKeyForm(forms.ModelForm):
    key = forms.CharField()

    class Meta:
        model = SecretKey
        fields = ['user', 'name', 'key', 'is_public']

    def __init__(self, *args, **kwargs):
        instance = kwargs.get('instance')
        initial = kwargs.get('initial', {})
        if instance:
            initial['key'] = instance.decrypt_key()
        kwargs['initial'] = initial
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.encrypt_key(self.cleaned_data['key'])
        if commit:
            instance.save()
        return instance
    
class ChatSessionCreateForm(forms.ModelForm):
    template = forms.ModelChoiceField(queryset=ChatTemplate.objects.none())

    class Meta:
        model = ChatSession
        fields = ['title', 'template', 'function_approval_required']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ChatSessionCreateForm, self).__init__(*args, **kwargs)
        if self.user:
            self.fields['template'].queryset = ChatTemplate.objects.filter(
                Q(is_public=True) | Q(user=self.user)).order_by('-user', 'name')

    def save(self, commit=True):
        instance = super(ChatSessionCreateForm, self).save(commit=False)
        instance.user = self.user
        if instance.template.is_public or instance.template.user == self.user:
            if commit:
                instance.save()
            return instance
        else:
            raise ValidationError("You can only select a template that is public or belongs to you.")

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.core.paginator import Paginator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from .models import ChatSession, ChatMessage, FunctionSchema, ChatTemplate, FunctionServer
from django.db.models import Max, F
from django.http import JsonResponse
from django.core.paginator import Paginator
from .forms import ChatSessionCreateForm
from django.core.exceptions import ObjectDoesNotExist

class HomePage(View):
    def get(self, request):
        return render(request, 'main/homepage.html')

class Chats(LoginRequiredMixin, View):
    def get(self, request):
        chat_sessions = ChatSession.objects.filter(user=request.user).annotate(latest_message_time=Max('messages__created_at')).order_by(F('latest_message_time').desc(nulls_last=True))
        if chat_sessions.exists():
            first_chat_session = chat_sessions.first()
            chat_messages = ChatMessage.objects.filter(session=first_chat_session).order_by('created_at')
            
        else:
            first_chat_session = None
            chat_messages = []

        return render(request, 'main/chats.html', {'chat_sessions': chat_sessions, 'chat_messages': chat_messages,})

class ChatMessageList(LoginRequiredMixin, View):
    def get(self, request, session_id):
        try:
            session = ChatSession.objects.get(pk=session_id)
            if session.user != request.user:
                return JsonResponse({'error': 'Not authorized.'}, status=403)

            chat_messages = ChatMessage.objects.filter(session=session).order_by('created_at')
            chat_data = list(chat_messages.values('role', 'content', 'created_at'))
            
            return JsonResponse(chat_data, safe=False)
        except ChatSession.DoesNotExist:
            return JsonResponse({'error': 'Chat session not found.'}, status=404)
        
class FunctionsView(View):
    def get(self, request, *args, **kwargs):
        page_number = request.GET.get('page', 1)
        try:
            page_number = int(page_number)
        except ValueError:
            page_number = 1

        functions_list = FunctionSchema.objects.all().order_by('-created_at')

        paginator = Paginator(functions_list, 10)
        functions = paginator.get_page(page_number)

        return render(request, 'main/functions.html', {'functions': functions})

class TemplatesView(View):
    def get(self, request, *args, **kwargs):
        page_number = request.GET.get('page', 1)
        try:
            page_number = int(page_number)
        except ValueError:
            page_number = 1

        templates_list = ChatTemplate.objects.all().order_by('-created_at')

        paginator = Paginator(templates_list, 10)
        templates = paginator.get_page(page_number)

        return render(request, 'main/templates.html', {'templates': templates})

class CreateChatView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        form = ChatSessionCreateForm(user=request.user)
        return render(request, 'main/create_chat.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = ChatSessionCreateForm(request.POST, user=request.user)
        if form.is_valid():
            chat = form.save(commit=False)
            chat.user = request.user

            try:
                chat.function_server = FunctionServer.objects.filter(is_public=True).first()
                if chat.function_server is None:
                    raise ObjectDoesNotExist

                chat.save()
                messages.success(request, "Chat session has been created successfully.")
                return redirect('chats')
            except ObjectDoesNotExist:
                messages.error(request, 'No public Function Servers available.')
                return render(request, 'main/create_chat.html', {'form': form})
        else:
            messages.error(request, 'There was a problem creating the chat session.')
            return render(request, 'main/create_chat.html', {'form': form})

main/templates/main/chats.html
{% extends "base/base.html" %}
{% load custom_filters %}
{% load static %}

{% block content %}
<div class="row" style="height: 80vh;">
  <div class="col-4 col-md-3 overflow-y-scroll h-100">
    <p class="text-center"><a href="{% url 'create_chat' %}">Create new chat</a></p>
    <ul class="list-group" id="chat_sessions_container">
      {% for chat in chat_sessions %}
        {% if forloop.first %}
        <li class="list-group-item active" aria-current="true" onclick="fetchChatMessages({{ chat.id }})" id="session-{{ chat.id }}">{{ chat.title|truncate_chars:70 }}</li>
        {% else %}
        <li class="list-group-item" onclick="fetchChatMessages({{ chat.id }})" id="session-{{ chat.id }}">{{ chat.title|truncate_chars:70 }}</li>
        {% endif %}
      {% endfor %}
      </ul>
  </div>

  <div class="col-8 col-md-9 d-flex flex-column justify-content-end h-100">
    <ul class="list-group" id="chat_messages_container" style="flex-grow: 1; overflow-y: auto;">
      {% for message in chat_messages %}
        <li class="list-group-item" style="white-space: pre-line;"><b>{{ message.role }}</b> : <span>{{ message.content }}</span></li>
      {% endfor %}
    </ul>
    
    <div class="d-flex align-items-center">
      <div class="btn-group dropup">
        <button type="button" class="btn btn-secondary" data-bs-toggle="dropdown" aria-expanded="false" style="border-radius: 0.25rem;">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-double-up"
            viewBox="0 0 16 16">
            <path fill-rule="evenodd"
              d="M7.646 2.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 3.707 2.354 9.354a.5.5 0 1 1-.708-.708l6-6z" />
            <path fill-rule="evenodd"
              d="M7.646 6.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 7.707l-5.646 5.647a.5.5 0 0 1-.708-.708l6-6z" />
          </svg>
        </button>
        <ul class="dropdown-menu" style="background-color: #f0eeee;">
          <li><button class="dropdown-item" id="invoke_ai"><b>Invoke AI</b></button></li>
          <li><button class="dropdown-item" id="invoke_function"><b>Invoke function</b></button></li>
        </ul>
      </div>
      <textarea class="form-control form-control-lg mb-2" rows="1" style="max-height: 200px; height: 24px; margin-left: 8px;"
        placeholder="Enter chat message" aria-label="Enter chat message" autofocus id="chat_input_box"></textarea>
      <button type="button" class="btn btn-primary btn-lg mb-2" style="margin-left: 8px;" id="chat_message_submit">></button>
    </div>

  </div>
</div>
<script src="{% static 'main/chat.js' %}"></script>
{% endblock %}

main/templates/main/create_chat.html
{% extends "base/base.html" %}
{% load custom_filters %}

{% block title %}Create a new chat | API for LLM{% endblock %}

{% block content %}
<p><b>Create a new chat:</b></p>

<form method="post" action="{% url 'create_chat' %}">
    {% csrf_token %}
    <div class="mb-3">
      <label for="id_title" class="form-label">Chat Title</label>
      {{ form.title|addclass_to_input:"form-control"|add_autofocus }}
      {% if form.title.errors %}
        <div class="alert alert-danger">
          {{ form.title.errors }}
        </div>
      {% endif %}
    </div>
    <div class="mb-3">
      <label for="id_template" class="form-label">Chat Template</label>
      {{ form.template }}
      {% if form.template.errors %}
        <div class="alert alert-danger">
          {{ form.template.errors }}
        </div>
      {% endif %}
    </div>
    <div class="mb-3 form-check">
      <input type="checkbox" class="form-check-input" id="id_function_approval_required" name="function_approval_required"
        {% if form.function_approval_required.value %}checked{% endif %}>
      <label class="form-check-label" for="id_function_approval_required">Function Approval Required</label>
      {% if form.function_approval_required.errors %}
      <div class="alert alert-danger">
        {{ form.function_approval_required.errors }}
      </div>
      {% endif %}
    </div>
    <button type="submit" class="btn btn-primary">Create Chat</button>
</form>

{% endblock %}

main/templates/main/functions.html
{% extends "base/base.html" %}
{% load custom_filters %}

{% block title %}Functions | Api for LLM{% endblock %}

{% block content %}
<p><b>Functions</b></p>

{% for function in functions %}
    <div class="function">
        <p><strong>Name:</strong> {{ function.name }}</p>
        <pre><strong>Schema:</strong> {{ function.schema|pretty_json }}</pre>
        <p>
            <strong>Created at:</strong> {{ function.created_at }} |
            <strong>Updated at:</strong> {{ function.updated_at }}
        </p>
        <hr>
    </div>
{% empty %}
    <p>You have not created any functions yet.</p>
{% endfor %}

{% if functions %}
<div style="text-align: center;">
    {% if functions.has_previous %}
        <a href="?page={{ functions.previous_page_number }}">Previous</a>
    {% endif %}

    Page {{ functions.number }} of {{ functions.paginator.num_pages }}

    {% if functions.has_next %}
        <a href="?page={{ functions.next_page_number }}">Next</a>
    {% endif %}
</div>
{% endif %}

{% endblock %}

main/templates/main/homepage.html
{% extends "base/base.html" %}

{% block content %}
    <b>API for LLM: Streamlining Access to Large Language Models</b>
    <br>
    <p>The best way to understand the site is through an example. Let's say you want to build an AI travel planner:</p>
    <ul>
        <li>Setting up: Begin by hosting various functions; one could compute optimal flight options, another might recommend hotel accommodations. After creating these functions, proceed to establish a chat template. This template will define system prompts to inquire about user travel preferences and dates, and link to the functions you've just created for flight and hotel suggestions.</li>
        <li>API Key Storage: Importantly, API for LLM provides secure storage for API keys, which can be passed to your functions. This enables your travel planner to integrate with multiple travel service APIs like Kayak for flights, Booking.com for hotels and Uber for local transport options.</li>
        <li>Launching the template on your website: After linking these functions to your chat template and selecting a large language model with an appropriate response temperature, you're ready to go. Each time a user starts a chat, an instance of the template is started. Users can then interact seamlessly with the AI, which internally leverages the defined functions to provide a comprehensive, tailored travel plan.</li>
    </ul>

    <br>
    <b>Additional info</b>
    <ul>
        <li>gpt-3.5 with 16k tokens context is being used. gpt-4 access is available for paying users.</li>
        <li>Functions run in Docker containers with gVisor for sandboxing currently, with potential plans for Firecracker in the future.</li>
        <li>There is no API yet; the chats are run on this website for testing.</li>
        <li>The site is under active development, numerous missing features are currently being worked on.</li>
    </ul>
    
{% endblock %}

main/templates/main/templates.html
{% extends "base/base.html" %}
{% load custom_filters %}

{% block title %}Templates | Api for LLM{% endblock %}

{% block content %}
<p><b>Templates</b></p>

{% for template in templates %}
    <div class="template">
        <p><strong>Name:</strong> {{ template.name }}</p>
        <p><strong>Model:</strong> {{ template.model }}</p>
        <p><strong>Temperature:</strong> {{ template.temperature }}</p>
        <p><strong>System prompt:</strong> {{ template.system_prompt|linebreaks }}</p>
        <p><strong>Functions:</strong></p>
        <ul>
        {% for function in template.functions.all %}
            <li>
                <strong>Name:</strong> {{ function.name }}
                <pre><strong>Schema:</strong> {{ function.schema|pretty_json }}</pre>
            </li>
        {% empty %}
            <li>No functions associated.</li>
        {% endfor %}
        </ul>
        <p>
            <strong>Created at:</strong> {{ template.created_at }} |
            <strong>Updated at:</strong> {{ template.updated_at }}
        </p>
        <hr>
    </div>
{% empty %}
    <p>You have not created any templates yet.</p>
{% endfor %}

{% if templates %}
<div style="text-align: center;">
    {% if templates.has_previous %}
        <a href="?page={{ templates.previous_page_number }}">Previous</a>
    {% endif %}

    Page {{ templates.number }} of {{ templates.paginator.num_pages }}

    {% if templates.has_next %}
        <a href="?page={{ templates.next_page_number }}">Next</a>
    {% endif %}
</div>
{% endif %}

{% endblock %}